//! AUTO-GENERATED Phase 2 factory for `BertSpladeSparseEmbeddingModel`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["BertSpladeSparseEmbeddingModel"];

static INFO: ArchInfo = ArchInfo::new("BertSpladeSparseEmbedding", Capabilities::empty());

pub struct BertSpladeSparseEmbeddingModelArchFactory;
pub static FACTORY: BertSpladeSparseEmbeddingModelArchFactory =
    BertSpladeSparseEmbeddingModelArchFactory;

impl ArchFactory for BertSpladeSparseEmbeddingModelArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(BertSpladeSparseEmbeddingModel::new(cfg, vb)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
