//! AUTO-GENERATED Phase 2 factory for `DbrxForCausalLM`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build, build_with_tp

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["DbrxForCausalLM"];

static INFO: ArchInfo = ArchInfo::new("Dbrx", Capabilities::TP);

pub struct DbrxArchFactory;
pub static FACTORY: DbrxArchFactory = DbrxArchFactory;

impl ArchFactory for DbrxArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(DbrxForCausalLM::new(cfg, vb)?))
    }

    fn build_with_tp(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
        pg: &dyn crate::distributed::ProcessGroup,
        tp_ctx: super::super::tp_layers::TpContext,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(DbrxForCausalLM::new_with_tp(cfg, vb, pg, tp_ctx)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
