//! AUTO-GENERATED Phase 2 factory for `DeepSeekForCausalLM`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build, build_quant, build_with_lora

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &[
    "DeepseekForCausalLM",
    "DeepseekV2ForCausalLM",
    "DeepseekV32ForCausalLM",
    "DeepseekV3ForCausalLM",
    "GlmMoeDsaForCausalLM",
    "MistralLarge3ForCausalLM",
];

static INFO: ArchInfo = ArchInfo::new(
    "DeepSeek",
    Capabilities::LORA.union(Capabilities::QUANTIZED),
);

pub struct DeepseekArchFactory;
pub static FACTORY: DeepseekArchFactory = DeepseekArchFactory;

impl ArchFactory for DeepseekArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(DeepSeekForCausalLM::new(cfg, vb)?))
    }

    fn build_quant(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder<'static>,
        weight_loader: &dyn crate::quantization::QuantizedWeightLoader,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(QuantizedDeepSeekForCausalLM::new(
            cfg,
            vb,
            weight_loader,
        )?))
    }

    fn build_with_lora(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<super::super::LoraEnabledModel, ModelError> {
        Ok(LoraEnabledModel::DeepSeek(DeepSeekWithLora::new(cfg, vb)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
