//! AUTO-GENERATED Phase 2 factory for `EagleLlamaForCausalLM`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: speculative_eagle1

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["EagleLlamaForCausalLM"];

static INFO: ArchInfo = ArchInfo::new("EagleLlama", Capabilities::SPECULATIVE_DRAFT);

pub struct EagleLlamaArchFactory;
pub static FACTORY: EagleLlamaArchFactory = EagleLlamaArchFactory;

impl ArchFactory for EagleLlamaArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
