//! AUTO-GENERATED Phase 2 factory for `Eagle3LlamaForCausalLM`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: speculative_eagle3

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &[
    "Eagle3LlamaForCausalLM",
    "Eagle3Qwen2_5vlForCausalLM",
    "Eagle3Qwen3vlForCausalLM",
    "LlamaForCausalLMEagle3",
];

static INFO: ArchInfo = ArchInfo::new("Eagle3Llama", Capabilities::SPECULATIVE_DRAFT);

pub struct Eagle3LlamaArchFactory;
pub static FACTORY: Eagle3LlamaArchFactory = Eagle3LlamaArchFactory;

impl ArchFactory for Eagle3LlamaArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
