//! AUTO-GENERATED Phase 2 factory for `GemmaForCausalLM`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build, build_quant, build_with_lora, build_with_tp

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["GemmaForCausalLM"];

static INFO: ArchInfo = ArchInfo::new(
    "Gemma",
    Capabilities::LORA
        .union(Capabilities::QUANTIZED)
        .union(Capabilities::TP),
);

pub struct GemmaArchFactory;
pub static FACTORY: GemmaArchFactory = GemmaArchFactory;

impl ArchFactory for GemmaArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(GemmaForCausalLM::new(cfg, vb)?))
    }

    fn build_quant(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder<'static>,
        weight_loader: &dyn crate::quantization::QuantizedWeightLoader,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(QuantizedGemmaForCausalLM::new(
            cfg,
            vb,
            weight_loader,
        )?))
    }

    fn build_with_tp(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
        pg: &dyn crate::distributed::ProcessGroup,
        tp_ctx: super::super::tp_layers::TpContext,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(GemmaForCausalLM::new_with_tp(
            cfg, vb, pg, tp_ctx,
        )?))
    }

    fn build_with_lora(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<super::super::LoraEnabledModel, ModelError> {
        Ok(LoraEnabledModel::Gemma(GemmaWithLora::new(cfg, vb)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
