//! AUTO-GENERATED Phase 2 factory for `Gemma2ForCausalLM`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build, build_quant, build_with_lora, build_with_tp

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["Gemma2ForCausalLM", "Gemma2Model"];

static INFO: ArchInfo = ArchInfo::new(
    "Gemma2",
    Capabilities::LORA
        .union(Capabilities::QUANTIZED)
        .union(Capabilities::TP),
);

pub struct Gemma2ArchFactory;
pub static FACTORY: Gemma2ArchFactory = Gemma2ArchFactory;

impl ArchFactory for Gemma2ArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(Gemma2ForCausalLM::new(cfg, vb)?))
    }

    fn build_quant(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder<'static>,
        weight_loader: &dyn crate::quantization::QuantizedWeightLoader,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(QuantizedGemma2ForCausalLM::new(
            cfg,
            vb,
            weight_loader,
        )?))
    }

    fn build_with_tp(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
        pg: &dyn crate::distributed::ProcessGroup,
        tp_ctx: super::super::tp_layers::TpContext,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(Gemma2ForCausalLM::new_with_tp(
            cfg, vb, pg, tp_ctx,
        )?))
    }

    fn build_with_lora(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<super::super::LoraEnabledModel, ModelError> {
        Ok(LoraEnabledModel::Gemma2(Gemma2WithLora::new(cfg, vb)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
