//! AUTO-GENERATED Phase 2 factory for `Glm4MoeMtpModel`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: speculative_mtp

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["Glm4MoeLiteMTPModel", "Glm4MoeMTPModel"];

static INFO: ArchInfo = ArchInfo::new("Glm4MoeMtp", Capabilities::SPECULATIVE_DRAFT);

pub struct Glm4MoeMtpModelArchFactory;
pub static FACTORY: Glm4MoeMtpModelArchFactory = Glm4MoeMtpModelArchFactory;

impl ArchFactory for Glm4MoeMtpModelArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
