//! AUTO-GENERATED Phase 2 factory for `GteNewForSequenceClassification`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["GteNewForSequenceClassification"];

static INFO: ArchInfo = ArchInfo::new("GteNewForSequenceClassification", Capabilities::empty());

pub struct GteNewForSequenceClassificationArchFactory;
pub static FACTORY: GteNewForSequenceClassificationArchFactory =
    GteNewForSequenceClassificationArchFactory;

impl ArchFactory for GteNewForSequenceClassificationArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(GteNewForSequenceClassification::new(cfg, vb)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
