//! AUTO-GENERATED Phase 2 factory for `MistralForCausalLM`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build, build_quant, build_with_lora, build_with_tp,
//! build_with_pp

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::distributed::PipelineStageConfig;
use crate::engine::{ModelForward, PipelineForward};

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["MistralForCausalLM"];

static INFO: ArchInfo = ArchInfo::new(
    "Mistral",
    Capabilities::LORA
        .union(Capabilities::QUANTIZED)
        .union(Capabilities::TP)
        .union(Capabilities::PP),
);

pub struct MistralArchFactory;
pub static FACTORY: MistralArchFactory = MistralArchFactory;

impl ArchFactory for MistralArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(MistralForCausalLM::new(cfg, vb)?))
    }

    fn build_quant(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder<'static>,
        weight_loader: &dyn crate::quantization::QuantizedWeightLoader,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(QuantizedMistralForCausalLM::new(
            cfg,
            vb,
            weight_loader,
        )?))
    }

    fn build_with_tp(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
        pg: &dyn crate::distributed::ProcessGroup,
        tp_ctx: super::super::tp_layers::TpContext,
    ) -> Result<Box<dyn ModelForward>, ModelError> {
        Ok(Box::new(MistralForCausalLM::new_with_tp(
            cfg, vb, pg, tp_ctx,
        )?))
    }

    /// Mistral PP routes through the Llama backbone (the legacy
    /// `from_config_with_pp` arm did the same — Mistral and Llama
    /// share the dense decoder layout, so the pipeline stage logic
    /// reuses Llama's implementation).
    fn build_with_pp(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
        stage: &PipelineStageConfig,
    ) -> Result<Box<dyn PipelineForward>, ModelError> {
        Ok(Box::new(
            super::super::llama::LlamaForCausalLM::new_with_pp(cfg, vb, stage)?,
        ))
    }

    fn build_with_lora(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<super::super::LoraEnabledModel, ModelError> {
        Ok(LoraEnabledModel::Mistral(MistralWithLora::new(cfg, vb)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
