//! AUTO-GENERATED Phase 2 factory for `NemotronParseForConditionalGeneration`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build_encoder_decoder

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["NemotronParseForConditionalGeneration"];

static INFO: ArchInfo = ArchInfo::new("NemotronParse", Capabilities::ENCODER_DECODER);

pub struct NemotronParseArchFactory;
pub static FACTORY: NemotronParseArchFactory = NemotronParseArchFactory;

impl ArchFactory for NemotronParseArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build_encoder_decoder(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn crate::engine::ModelForEncoderDecoder>, ModelError> {
        Ok(Box::new(
            nemotron_parse::NemotronParseForConditionalGeneration::new(cfg, vb)?,
        ))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
