//! AUTO-GENERATED Phase 2 factory for `T5ForConditionalGeneration`.
//!
//! Generated by `scripts/generate_factories.py` from the legacy match-arm
//! dispatch in `crates/core/src/models/mod.rs`. Bodies are lifted
//! verbatim — re-running the generator overwrites this file.
//!
//! Capabilities: build_encoder_decoder

#![allow(unused_imports, unused_variables)]

use std::any::Any;

use candle_nn::VarBuilder;

use crate::config::ModelConfig;
use crate::engine::ModelForward;

use super::super::factory::{ArchFactory, ArchInfo, Capabilities};
use super::super::*;

pub const ARCH_NAMES: &[&str] = &["T5ForConditionalGeneration", "T5Model"];

static INFO: ArchInfo = ArchInfo::new("T5", Capabilities::ENCODER_DECODER);

pub struct T5ArchFactory;
pub static FACTORY: T5ArchFactory = T5ArchFactory;

impl ArchFactory for T5ArchFactory {
    fn arch_names(&self) -> &'static [&'static str] {
        ARCH_NAMES
    }
    fn info(&self) -> &'static ArchInfo {
        &INFO
    }

    fn build_encoder_decoder(
        &self,
        cfg: &ModelConfig,
        vb: VarBuilder,
    ) -> Result<Box<dyn crate::engine::ModelForEncoderDecoder>, ModelError> {
        Ok(Box::new(T5ForConditionalGeneration::new(cfg, vb)?))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
