#!/usr/bin/env python3
"""
Phase 2.4 — populate `crates/core/src/models/registry_v2.rs` with one
`phf_map!` entry per arch_name, pointing at the factory's `&FACTORY`
static. Reads `ARCH_NAMES: &[&str]` from each `factories/*.rs` file.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ARCH_NAMES_RE = re.compile(
    r'pub const (?:[A-Z][A-Z0-9_]*_)?ARCH_NAMES: &\[&str\] = &\[(?P<body>.*?)\];',
    re.DOTALL,
)
NAME_RE = re.compile(r'"([^"]+)"')


def collect(factories_dir: Path) -> list[tuple[str, str]]:
    """Return list of (arch_name, module_short_name) pairs."""
    pairs: list[tuple[str, str]] = []
    for path in sorted(factories_dir.glob("*.rs")):
        if path.name == "mod.rs":
            continue
        short = path.stem
        text = path.read_text()
        m = ARCH_NAMES_RE.search(text)
        if not m:
            print(f"WARN: no ARCH_NAMES in {path.name}", file=sys.stderr)
            continue
        for name in NAME_RE.findall(m.group("body")):
            pairs.append((name, short))
    return pairs


REGISTRY_HEADER = '''\
//! Architecture registry — `phf::Map<arch_name, &dyn ArchFactory>`.
//!
//! AUTO-GENERATED by `scripts/generate_registry.py` from the
//! `factories/*.rs` files. Each `pub mod` in `factories/mod.rs`
//! contributes one or more entries (one per `ARCH_NAMES` element).
//!
//! Behind `--features model-registry-v2`. The cfg gate lives on the
//! `pub mod registry_v2;` declaration in `mod.rs`.

use phf::phf_map;

use super::factories;
use super::factory::ArchFactory;

/// Compile-time map from HuggingFace `architectures[]` strings to
/// `&'static dyn ArchFactory`. Duplicate keys would fail the `phf`
/// build, which is exactly the invariant we want.
pub static REGISTRY: phf::Map<&'static str, &'static dyn ArchFactory> = phf_map! {
'''

REGISTRY_FOOTER = '''\
};

pub fn lookup(arch: &str) -> Option<&'static dyn ArchFactory> {
    REGISTRY.get(arch).copied()
}

pub fn entries() -> impl Iterator<Item = (&'static str, &'static dyn ArchFactory)> {
    REGISTRY.entries().map(|(k, v)| (*k, *v))
}

pub fn len() -> usize {
    REGISTRY.len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_is_populated() {
        assert!(len() > 0);
        assert!(lookup("LlamaForCausalLM").is_some());
    }

    #[test]
    fn registry_resolves_canonical_archs() {
        for arch in [
            "LlamaForCausalLM",
            "Qwen2ForCausalLM",
            "MixtralForCausalLM",
            "MistralForCausalLM",
            "Gemma3ForCausalLM",
            "DeepseekV3ForCausalLM",
        ] {
            assert!(lookup(arch).is_some(), "missing: {arch}");
        }
    }
}
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--factories-dir", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    pairs = collect(args.factories_dir)
    # Deduplicate (a single arch_name appearing in two factory files is
    # a bug — phf would fail anyway, but warn loudly here).
    seen: dict[str, str] = {}
    for arch, short in pairs:
        if arch in seen and seen[arch] != short:
            print(
                f"WARN: arch_name '{arch}' claimed by both '{seen[arch]}' and '{short}'",
                file=sys.stderr,
            )
            continue
        seen[arch] = short

    entries = ",\n".join(
        f'    "{a}" => &factories::{m}::FACTORY as &dyn ArchFactory'
        for a, m in sorted(seen.items())
    ) + ","
    out = REGISTRY_HEADER + entries + "\n" + REGISTRY_FOOTER
    args.out.write_text(out)
    print(f"wrote {len(seen)} arch entries to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
